---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: cert-manager
spec:
  image: "quay.io/jetstack/charts/cert-manager"
  interval: 12h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: cert-manager
spec:
  imageRepositoryRef:
    name: cert-manager
  policy:
    semver:
      range: ">=1.0.0"
